version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      github-actions:
        patterns:
          - '*'
    target-branch: develop
    labels:
      - dependencies

  - package-ecosystem: 'composer'
    directory: '/'
    schedule:
      interval: 'daily'
    allow:
      - dependency-type: 'all'
    ignore:
      - dependency-name: '*'
        update-types: ['version-update:semver-major']
    groups:
      website:
        patterns:
          - '*'
    target-branch: develop
    labels:
      - dependencies
